# String Search {#strsearch}

## Substring

How would you go about solving the following question?

<i>Given a string <b>S</b> and a text <b>T</b>, look for an occurrence of <b>S</b> as a substring of <b>T</b></i>

Should you return all occurrences of the substring <b>S</b>, or just the first occurrence. And what should you return to indicate if it has been found?

* If you are only looking for the first occurrence, you could return the index of the first character of S in T; otherwise return -1.

What would the complexity be of this operation?

### Example

Find the string "vtewfvtxqwfczsrdzcaj" in the text:

```
ddtubshmfrjmcvxapjgcnmofsdanwfnanovxkbzueekgsenzonxdbjstogivsgbegwdxennghuycrj
pqjntsapyqavaywsjmpsryfnqsdxsqafbckugtzcbmzafjvhfiehyxjhiumsohonxxdvfroklswyzb
waxritoazzdbkaoswcfznytojsizcgpdqobakvfxnewamtbfwtjyrddhqxcaqzvdttuoudxuiippzs
xnprlgwpakgrlvvqfkezesbpgcstqvifqflcvjodhvcbrhorehrtroiuiqfgonublbtwzzbnjwpspq
wbolnqvelzzlzlqixqihnhhkezhsfjaohdjoxtukxjrunxfmjdxtjcnjlqkdkujsjthnabhhsxfpgz
eyjmrjeybwudpdlstsqkbfrgirlhrymymngvodzeqwhvlimyomselaydohldowfvikjqdkzdmmciub
befdsmfuukrqdefmeypsedppfczenrdyemgrppnguuiblswygokwvvwxaoabnqrtbfmmsxjvwiltzb
kdxomjfrbqgclwyjzzltfjxxkstbjqrqcahatzkdmnvtqxpogkfnznxvelpnkoaqhsiopktycfrhwj
iywabnjfmjuupqxtghzjigylobfrughnhboiiauqgdaxumftaugyytvunhrsfzbdjbkkoumpynnvch
qhkezzurtfprwqqkrjmjravkervxwnnupthnvasqdbtoakaywkvpnvnrbejlsgoegrqwfiiabwzgoy
```

Some of the main variations of substring searching include:

* Check whether it is there, returning a boolean
* Find the first/last occurrence of `S` in `T`
* Find all occurrences of `S` in `T`
  * What if occurrences overlap
* Find occurrences as a whole word
* Find occurrences within lines or allow occurrences to occur across line breaks

In Java the first two variations can be accomplished with

* `T.indexOf(S)`
* `T.lastIndexOf(S)`
* `T.contains(S)`

Do the above methods have good algorithmic complexity or is it possible to achieve better results.

## Naive/Brute force approach

A simple and inefficient way to see if one string is a substring of another is to check each character one by one. So first we see if there's a copy of `S` in the first character of `T`; if not, we look to see if there's a copy of `S` at the character of `T` and so forth. 

* Look for occurrences of string `S` in string `T` starting at positions `T[0]`, `T[1]`, ... up to` T[T.length() - S.length()]`:

```java
for (int i = 0; i < T.length() - S.length(); i++) {
  if (T.substring(i, S.length())).equals(S))
    return i;
}
return -1;
```

Micro optimization's can be made to the above algorithm to improve its performance:

* Don't call the length method in the loop. Avoid the cost of the method call (some compilers may inline it)
* Don't call the substring method in the loop. Don't need to copy the substring to a new string to compare it with S.

```java
int m = S.length();
int n = T.length()

for (int i = 0; i < n-m; i++) {
  boolean found = true;
  for (int j = 0; j < m; j++) {
    if (S.charAt(i) != T.charAt(j + i) {
    found = false;
    break;
    }
  }
  if (found)
    return i;
}
return -1
```

## Efficiency

The best case occurs in two scenario's

1. When `S[0]` does not occur at all in `T`:
    * `S[0]` will be compared to `T[0]`
    * `S[0]` will compared to `T[1]`
    * ... `S[0]` will be compared to` T[n-m]`
  
2. When `S` is a prefix of `T` e.g. "car" and "carpet"
    * `S[0]` will be compared to `T[0]`
    * `S[1]` will be compared to `T[1]`
    * ...`S[m]` will be compared to `S[m]`
  
The above two situations have a cost of $O(n)$ and $O(m)$ respectively.  
  
The average cost is bit more difficult to reason about and occurs when `S` is a substring of `T` and you only have to look at one or two characters in `S` at each wrong position in `T` to see that it is the wrong position. So in the average case the efficiency is $O(n + m)$.


The worst case case occurs when searching for a string like `S = "aaaaaab"` in `T = "aaaaaaaaaaaaaaaaaaaaa"`. 

* `S` is not in `T`, so it will search fully through `T` (up to `T[n-m]`) 
* At each position in `T`, the algorithm will check up to `S[m-1]`  characters.

In this case the algorithm will try the maximum number of positions in T and do the most possible comparisons before failing, giving a cost of $O(nm)$.



## Knuth-Morris-Pratt (KMP) algorithm

The KMP algorithm works by employing the observation that when a mismatch occurs, the word itself embodies sufficient information to determine where the next match can begin, thus bypassing the need to reexamine characters in `T` more than once.

To illustrate the algorithm's details consider a run where the inputs are:

```
T = abc_abcdab_abcdabcdabde
S = abcdabd
```

At any given time, the algorithm is in a state determined by two integers:

* `m`, denoting the position within `T` where the prospective match for `S` begins
* `i`, denoting the index of the currently considered character in `S`

In each step the algorithm compares `T[m+i]` with `S[i]` and increments `i` if they are equal. This is depicted at the start of the run, like:

<div>
<pre>
T = <span style='color: green;'>abc</span>_abcdab_abcdabcdabde  
S = <span style='color: green;'>abc</span><span style='color: red;'>d</span>abd  
i = 0123  
m = 0123  
</pre>
</div>

The algorithm compares successive characters of `S` to "parallel" characters of `T`, moving from one to the next by incrementing `i` if they match. However, in the fourth step `T[3] = '_'` does not match `S[3] = 'd'`. Rather than beginning the search again at `T[1]`, we note that no 'a' occurs between positions 1 and 2 in `T`; hence having checked all those characters previously (and knowing they matched the corresponding characters in `S`), there is no chance of finding the beginning of a match. Therefore, the algorithm sets `m = 3` and `i = 0`.

<div>
<pre>
T = abc_abcdab_abcdabcdabde  
S =    <span style='color: red;'>a</span>bcdabd   

i = <span style='color: lightgrey;'>012</span>0
m = 0123
</pre>
</div>

This match fails at the initial character, so the algorithm sets` m = 4` and `i = 0`.

<div>
<pre>
T = abc_<span style='color: green;'>abcdab</span>_abcdabcdabde  
S =     <span style='color: green;'>abcdab</span><span style='color: red;'>d</span>  
              1
i = <span style='color: lightgrey;'>0120</span>0123456  
m = <span style='color: lightgrey;'>0123</span>4567890  
</pre>
</div>

Here, `i` increments through nearly the correct match `abcdab` until `i = 6` giving a mismatch at `S[6]` and `T[10]`. However, just prior to the end of the current partial match , the substring `"ab"` occurred and this could be the beginning of a new match, so the algorithm must take this into consideration. As these characters match the previous two characters prior to the current position, those characters need not be checked again; the algorithm sets `m = 8` and `i = 2` and continues matching. The algorithm not only omits previously matched characters in `T` (the `"ab"`), but also previously matched characters in `W` (the prefix `"ab"`)

<div>
<pre>
T = abc_abcd<span style='color: green;'>ab</span>_abcdabcdabde
S =         <span style='color: green;'>ab</span><span style='color: red;'>c</span>dabd
              1
i = <span style='color: lightgrey;'>01200123</span>012
m = <span style='color: lightgrey;'>01234567</span>890
</pre>
</div>

The search at the new position fails immediately because `S[2] = 'c'` does not match `T[10] = '_'`. As in the first trial, the mismatch causes the algorithm to return to the beginning of `S` and begins searching at the mismatched character position of `T`; `m = 10`, reset `i = 0`.

<div>
<pre>
T = abc_abcdab_abcdabcdabde
S =           <span style='color: red;'>a</span>bcdabd
              1
i = <span style='color: lightgrey;'>0120012301</span>0
m = <span style='color: lightgrey;'>0123456789</span>0
</pre>
</div>

The match at `m = 10` fails immediately, so the algorithm next tries `m = 11` and `i = 0`


<div>
<pre>
T = abc_abcdab_<span style='color: green;'>abcdab</span>cdabde
S =            <span style='color: green;'>abcdab</span><span style='color: red;'>d</span>
              1
i = <span style='color: lightgrey;'>01200123010</span>0123456
m = <span style='color: lightgrey;'>01234567890</span>1234567
</pre>
</div>

Once again, the algorithm matches `"abcdab"`, but the next character `'c'`, does not match the final character `'d'` of the word `S`. Reasoning as before, the algorithm sets `m = 15`, to start athe two-character string `"ab"` leading up to the current position, set `i = 2`, and continue mathcing from the current position.

<div>
<pre>
T = abc_abcdab_abcd<span style='color: green;'>abcdabd</span>e
S =                <span style='color: green;'>abcdabd</span>
              1          2
i = <span style='color: lightgrey;'>012001230100123</span>0123456
m = 012345678901234</span>5678901
</pre>
</div>

This time the match is complete, and the first character of the match is `S[15]`


### Java Code


```java
int kmpSearch(String needle, String haystack, int[] partialMatches) {
  int j = 0; # Position of the current character in the needle
  int k = 0; # Position of the current character in the haystack
  int m = needle.length();
  int n = haystack.length();
  
  while (j + k < n) {
    if (needle.charAt(j) = haystack.charAt(k)) {
      j++;
      k++;
      if (j==m)
        return k - m; // return the first occurence of the needle in the haystack
    }
    else if (partialMatches[j] == -1) { // Mismatch, no self overlap
      k += j;
      j = 0; // needle starts at beginning
    }
    else { // Mismatch with self overlap
      k += j - partialMatches[j]  // Match position to jump forward
      j = partialMatches[j]
    }
  }
  return -1;
}
```

### Efficiency

Ignoring the complexity of computing the partial match table, the search portion of the KMP algorithm has complexity `O(n)` where `n` is the length of the search string, `S`. All computations inside and outside of the `while` loop have `O(1)` efficiency.


To bound the number of iterations of the loop; observe that `M` is constructed so that if a match which had begun at `T[k]` fails while comparing `T[k + j]` to `S[j]`, then the next possible match must begin at` T[k + (j - M[j])]`. In particular, the next possible match must occur at a higher index than `j`, so that `M[j] < j`.

This fact implies that the loop can execute at most `2n` times, since at each iteration it executes one of the two (mismatch) branches in the loop:

1. The first branch increases `k` by `j`, so that the index `k + j` of the currently scrutinized character of `T` (`T[k]`) is increased. 
2. The second branch adds `j - M[j]` to `k`, and as we have seen, this is always a positive number. Thus the location `k` of the beginning of the current potential match is increased. At the same time, the second branch leaves `k + j` unchanged, for `k` gets `j - M[j]` added to it, and immediately after `M[j]` gets assigned as the new value of `j`.
  * Hence `new_k + new_j = old_k + old_j - M[old_j] + M[old_j] = old_k + old_j.`

Now, the loop ends if `j + k = n`; therefore, each branch of the loop can be reached at most `n` times, since they respectively increase either `k + j` or `k`, and `j ≤ j + k`: if `k = n`, then certainly `k + j ≥ n`, so that since it increases by unit increments at most, we must have had `k + j = n` at some point in the past, and therefore either way we would be done.

Thus the loop executes at most `2n` times, showing that the time complexity of the search algorithm is `O(n)` (Bound by the length of the word being searched).


### KMP Partial Match Table

Each time a mismatch between `S[j]` and `T[k]` occurs, we need to advance to the earliest place in `T` where the search string could possibly match. This avoids re-checking of characters that the brute-force method does. 

How do we work out how far we can safely advance? This is determined by whether there is a prefix of matching characters in `S` equal to a suffix of matching characters in `T`.


<div>
<pre>
<span style='color: green;'>abbabbtabbarsaa</span>
abbabb<span style='color: red;'>c</span>zz
   abb<span style='color: red;'>a</span>bbzz
       abba<span style='color: red;'>b</span>bczz
           <span style='color: lightgrey;'>a</span>bbabbczz
</pre>
</div>

1. If there isn't a `S.prefix == T.suffix`. Skip all characters in the overlap of characters in `S` and `T` that do match.
    * Start from `T[i]` and `S[0]`, where `i` is the position of the character in `T` that did not match to the character in `S`
2. If there is a `S.prefix == T.suffix`. Skip all characters in the overlap of matching prefix and suffix characters in `S` and `T`
    * Start from `T[i]` and `S[j]` where `i` is the position in `T` after the suffix overlap and `j` is the position in `S` after the prefix overlap. 
  
A table is generally used for storing this information. Called `M` with length `m` and based on the search string `S` can be used to determine how far to advance the search if a prefix of `S` has been matched.

If there is a mismatch in `S` at position `j` and in `T` at position `k`:

<div>
<pre>
T = an<span style='color: blue;'>an</span><span style='color: red;'>x</span>???...
S = <span style='color: green;'>an</span>an<span style='color: red;'>c<span>ba
</pre>
</div>

1. Find the longest <span style='color: blue;'>suffix in <code>T</code></span> (prior to the mismatch position) that matches a <span style='color: green;'>prefix in <code>S</code></span>.
2. Move `k` forward by `j` minus the length of the prefix/suffix substring.
  * `k +=  j - prefix.length()` or `k +=  j - suffix.length()`
3. Set `j` to the length of the prefix/suffix substring
  * `j = prefix.length()` or `j = suffix.length()`
  
There is a special case where if `suffix.length()/prefix.length()` (i.e. there is overlapping prefix and suffix):

  1. `k += 1` (Start from the next position in `T`)
  2. `j = 0` (Start matching from the first position in `S`)
  
  <b>Note</b> a suffix of a partial match in `S` is part of the search string, only the search string needs to be analyzed to find all partial matches.
  
  
#### Example

We will walk through building the partial match table for the search string `"abcdabd"`


1. Set `W[0] = -1` as a mismatch at the very start of the search string is a special case.

2. To find `M[1]`, we need to find a proper suffix of `"a"` which is also a prefix of the search string `S`. But there are no proper suffixes^[a proper suffix is a substring of `S` that is not equal to `S` itself, hence `"a"` is not a proper suffix of `"a"`] of `"a"`, so `M[1] = 0`

3. To find `M[2]`, we see that the substring `S[0]` to `S[1]` (`"ab"`) has a proper suffix `"b"`. However `"b"` is not a prefix of the pattern `S`, so we set `M[2] = 0`
4. Continuing to `M[3]`, we first check the proper suffix of length 1, and as in the previous case it fails. Do we need to check the longer suffixes? No we know that there is a shortcut to checking <i>all</i> suffixes. Let us say that we discovered a proper suffix which is a proper prefix (A proper prefix of a string is not equal to the string itself) and ending at `S[2]` with length 2 (maximum possible); then its first character is also a proper prefix of `S`, hence a proper prefix itself, and it ends at `S[1]`, which we already determined did not occur as `M[2] = 0` and not `M[2] = 1`. Hence at each stage, the shortcut rule is that one needs to consider checking suffixes of a given size `m+1` only if a valid suffix of size `m` was found at the previous stage (i.e. `M[x] = m`) and should not bother to check `m+2`,`m+3`, etc. Therefore, we need not even concern ourselves with search terms having length 2, and as in the previous case the sole one with length 1 fails, so `M[3] = 0`.

5. We pass to the subsequent `S[4]`, `'a'`. The same logic shows that the longest substring we need to consider has length 1, and as in the previous case it fails since `'d'` is not a prefix of `S`. so `M[4] = 0`

6. Considering the next character, `S[5]`, which is `'b'`: through inspection the longest substring would is `'a'`, therefore `M[5] = 1`. 

7. Finally, we see that the next character in the ongoing segment starting at `S[4] = 'a'` would be `'b'`, and indeed this is also `S[5]`. Furthermore, the same argument as above shows that we need not look before `S[4]` to find a segment for `S[6]`, so that is it and we take `M[6] = 2`


<table class="wikitable" style="background-color:white; font-family:monospace; text-align:right">
<tbody><tr>
<th><code>i</code>
</th>
<td>0
</td>
<td>1
</td>
<td>2
</td>
<td>3
</td>
<td>4
</td>
<td>5
</td>
<td>6
</td>
<td>7
</td></tr>
<tr>
<th><code>S[i]</code>
</th>
<td>a
</td>
<td>b
</td>
<td>c
</td>
<td>d
</td>
<td>e
</td>
<td>b
</td>
<td>d
</td>
<td>
</td></tr>
<tr>
<th><code>M[i]</code>
</th>
<td>-1
</td>
<td>0
</td>
<td>0
</td>
<td>0
</td>
<td>0
</td>
<td>1
</td>
<td>2
</td>
<td>0
</td></tr></tbody></table>  
  
  
### Computing the Partial Match Table


```java

int[] computeKmpTable(String needle) {
  int m = needle.length();
  int[] kmpTable = new int[m]
  
  kmpTable[0] = -1;
  int pos = 1; // The current position we are computing in the KMP partial match table
  int j = 0 // The index in the prefix of the needle
  
  while (pos < m) {
    if (needle.charAt(pos).equals(needle.charAt(j))) { // substrings at ...pos (suffix) and 0...j (prefix) match
       kmpTable[pos] = j;
       pos++;j++
    }
    else if (j > 0) { // Mismatch, restart the prefix
      j = kmpTable[j];
      
    }
    else { // We have run out of candidate prefixes
      kmpTable[pos] = 0;
      pos++;
    }
  }
}
```

`kmpTable[i]` represents where to start matching in `S` after a mismatch at `i + 1` i.e. the length of the longest suffix that is also a prefix of the string
from index `0` to index `i`

### Efficiency

The `while` loop begins at 1 and the upper bound on the loop is `pos < m` the length of the search string. Every iteration of the loop `pos` is incremented by 1, thus the loop will take <i>`m - 1`</i> iterations. The complexity is `O(m)`.

The overall efficiency of the KMP algorithm is `O(n + m)`


## Boyer-Moore